### ISSUE TITLE
jekyll-compass & Github-hosted sites

### ISSUE THREAD

**Issue by jdsteinbach** [mscharley/jekyll-compass#30]
Quick question: is this plugin compatible with a Jekyll site hosted & auto-built by Github?

**Comment by mscharley** [comment]
Technically, it could be as it does support safe mode, but to my knowledge Github Pages doesn't allow the usage of any plugins at all.

The main option people go with to get around this is to precompile plugin output into the source folder so that GitHub Pages will see it and just copy the static versions across. I've specifically designed jekyll-compass to avoid putting files into the source folder but you might have a few options:

1. You should *probably* be able to set the `css_path` option to somewhere inside your source folder using relative paths. Not sure how stable this option would be.
2. While developing, delete the CSS folder in your source folder. Once you're happy with your site locally, copy the new version of your CSS files into your source folder again.

GitHub pages wasn't my primary audience when building this due to their lack of plugin support but if you do get it working then please do reply back!

**Comment by jdsteinbach** [comment]
Thanks for the reply. Looks like GH Pages has a shortlist of 4 plugins they support. The reason I'm using Compass (not just Sass) is that I've got a function that relies on exponential math that Compass does right, but the helper function I've put in Sass does wrong. I'm probably better off finding a better way to write that function, as opposed to complicating my build/push process.

**Comment by mscharley** [comment]
Looks like they only support plugins by the official Jekyll team. Not sure what could be done about getting jekyll-compass into that sort of company, though @parkr may be able to shed some light on it. For my part, I haven't worked on this plugin in a while now, though it gets regular traffic with little complaint so I can only assume it still works well with the latest versions. There's currently only the one minor issue (#14) keeping it from running well in safe mode as well.

**Comment by yuvadm** [comment]
:+1: this, would like to see GitHub Pages support.

**Comment by parkr** [comment]
If you write into support@github.com explaining why Sass isn't enough and you need Compass, I'm sure they'd be willing to explain what can be done.

**Comment by mscharley** [comment]
Thanks for the response @parkr.

Guys, I'm happy to help facilitate discussion, but if there's actual users wanting this then you can probably articulate to GitHub support your use-cases better than I can.

As for this project specifically, as mentioned before, there's only one relatively minor (in terms of ease to fix) issue open against safe-mode and I'm always open to more bug reports in this or any other area.

**Comment by francoisromain** [comment]
Github support suggested to build the site locally and upload only the content of the `_site` folder on github. So I end up with two repos: 
- one with the full jekyll stuffs 
- one with only a copy of the _site folder only which is uploaded to github

I use an alias in my bash profile to automate the copy to the site folder, commit and push to Github. Like so: 

     alias blog="cd [url/of/local/repo] && jekyll build && cp -rf _site/ [url/of/local/_site-repo] && cd [url/of/local/_site-repo] && git add . && git commit -m "\""Update `date '+%Y-%m-%d'`"\"" && git push origin master"
